export const dessertsMenuItems = [
  // Desserts Section
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Gebackene Banane (4 Stück)',
    price: '5,90 €',
    description: 'Banane in Pankomehl umhüllt verfeinert mit Honig, Kokosraspeln und Mandeln',
    image: '/BOWLICIOUS/Gebackene Banane (4 Stück).webp',
    tags: [],
    order: 1,
    active: true,
  },
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Kokos Mochi (3 Stück)',
    price: '5,90 €',
    description: 'kleine japanische Reisküchlein mit Kokos-Eis innen drin',
    image: '/BOWLICIOUS/Kokos Mochi (3 Stück).webp',
    tags: [],
    order: 2,
    active: true,
  },
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Creme Brulee',
    price: '5,90 €',
    description: 'Creme Brulee ist eine Süßspeise aus Eigelb, Sahne und Zucker, die als Dessert in der französischen Küche serviert wird.',
    image: '/BOWLICIOUS/Creme Brulee.webp',
    tags: [],
    order: 3,
    active: true,
  },
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Banana Pudding',
    price: '5,90 €',
    description: 'hausgemachter Banana Pudding - frische Bananenscheiben, luftige Vanillecreme und Eierkeksschichten, liebevoll geschichtet',
    image: '/BOWLICIOUS/Banana Pudding.webp',
    tags: [],
    order: 4,
    active: true,
  },
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Mango Cheesecake',
    price: '5,90 €',
    description: 'hausgemachtes Mango-Cheesecake mit Butterkeksboden',
    image: '/BOWLICIOUS/Mango Cheesecake.webp',
    tags: [],
    order: 5,
    active: true,
  },
  {
    restaurant: 'DESSERTS',
    section: 'Desserts',
    name: 'Glückskekse (1 Stück)',
    price: '0,70 €',
    description: '',
    image: '/BOWLICIOUS/Glückskekse (1 Stück).webp',
    tags: [],
    order: 6,
    active: true,
  },
]
