// DRINKS Menu Items - Complete Data

export const drinksMenuItems = [
  // Alkoholische Getränke Section
  {
    restaurant: 'DRINKS',
    section: 'Alkoholische Getränke',
    name: 'Corona Extra 0,33l',
    price: '3,80 €',
    description: '4,5% vol, 0,33l, 11,52 €/1l',
    image: '/HIRO BURGER/Corona Extra 0,33lAltersbeschränkung.webp',
    tags: [],
    order: 1,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholische Getränke',
    name: 'Saigon Premium',
    price: '3,80 €',
    description: '8% vol, 0,33l, 11,52 €/1l',
    image: '/HIRO BURGER/Saigon Premium.webp',
    tags: [],
    order: 2,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholische Getränke',
    name: 'Asahi',
    price: '3,80 €',
    description: '8% vol, 0,33l, 11,52 €/1l',
    image: '/HIRO BURGER/Asahi.webp',
    tags: [],
    order: 3,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholische Getränke',
    name: 'Tsingtao',
    price: '3,80 €',
    description: '8% vol, 0,33l, 11,52 €/1l',
    image: '/HIRO BURGER/Tsingtao.webp',
    tags: [],
    order: 4,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholische Getränke',
    name: 'Kirin Ichiban',
    price: '3,80 €',
    description: '8% vol, 0,33l, 11,52 €/1l',
    image: '/HIRO BURGER/Kirin Ichiban.webp',
    tags: [],
    order: 5,
    active: true,
  },

  // Alkoholfreie Getränke Section
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Lycheenektar 0.25l',
    price: '3,20 €',
    description: '0,25l, 12,80 €/1l',
    image: '/HIRO BURGER/Lycheenektar 0.25l.webp',
    tags: [],
    order: 1,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Aloe Vera 0.5l',
    price: '4,00 €',
    description: '0,5l, 8,00 €/1l',
    image: '/HIRO BURGER/Aloe Vera 0.5l.webp',
    tags: [],
    order: 2,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Mango Lassi 0.4l',
    price: '4,90 €',
    description: 'Ein cremiges Joghurtgetränk • 0,4l, 12,25 €/1l',
    image: '/HIRO BURGER/Mango Lassi 0.4l.webp',
    tags: [],
    order: 3,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Coca-Cola 0,33l (MEHRWEG)',
    price: '3,35 €',
    description: 'Coca-Cola steht für einzigartigen Geschmack, Erfrischung und Momente voller Lebensfreude. Die 0,33l Glas-Mehrwegflasche ist unsere Ikone für perfekten Trinkgenuss seit 1886. • zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l, Enthält Koffein (10mg/100ml)',
    image: '/HIRO BURGER/Coca-Cola 0,33l (MEHRWEG).webp',
    tags: [],
    order: 4,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Coca-Cola Zero Sugar 0,33l (MEHRWEG)',
    price: '3,35 €',
    description: 'Keine Kalorien. Null Zucker. Für alle Coke Liebhaber, die beim Geschmack keinen Kompromiss eingehen wollen. • zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l, Enthält Koffein (10mg/100ml)',
    image: '/HIRO BURGER/Coca-Cola Zero Sugar 0,33l (MEHRWEG).webp',
    tags: [],
    order: 5,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Kola 0,33l',
    price: '3,42 €',
    description: 'Unser Original: Die bessere Alternative mit einzigartigem Cola-Geschmack und viel Koffein. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l, Enthält Koffein (25mg/100ml)',
    image: '/HIRO BURGER/Fritz-Kola 0,33l.webp',
    tags: [],
    order: 6,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Limo Orange 0,33l',
    price: '3,42 €',
    description: 'Da scheint die Sonne aus dem Glas: Unsere Orangen-Limonade kommt dank mitmischender Zitrone und Mandarine auf intensive 17% Fruchtanteil. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l',
    image: '/HIRO BURGER/Fritz-Limo Orange 0,33l.webp',
    tags: [],
    order: 7,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Limo Zitrone 0,33l',
    price: '3,42 €',
    description: 'Wenn dir Zitronen das Leben geben, dann ist es Fritz-Limo. Mit vielen Zitronen für einen hohen Fruchtanteil. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l',
    image: '/HIRO BURGER/Fritz-Limo Zitrone 0,33l.webp',
    tags: [],
    order: 8,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Limo Honigmelone 0,33l',
    price: '3,42 €',
    description: 'Schmeckt unvergleichlich - denn wer macht aus Honigmelone schon Limonade? Die Antwort überrascht wohl nicht. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l',
    image: '/HIRO BURGER/Fritz-Limo Honigmelone 0,33l.webp',
    tags: [],
    order: 9,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Limo Apfel-Kirsch-Holunder 0,33l',
    price: '3,42 €',
    description: 'Die gibt dir \'nen Obstkorb: 23% Frucht von Äpfeln, Kirschen und Holunderbeeren - sauer-süß-herb. Keine Wünsche offen. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l',
    image: '/HIRO BURGER/Fritz-Limo Apfel-Kirsch-Holunder 0,33l.webp',
    tags: [],
    order: 10,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz-Spritz Bio-Apfelschorle 0,33l',
    price: '3,42 €',
    description: 'Die erste naturtrübe Apfelschorle auf dem Markt macht immer noch alles richtig: 66% Bio-Direktsaft für einen Geschmack, als wäre er geradewegs in die Flasche geerntet. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l',
    image: '/HIRO BURGER/Fritz-Spritz Bio-Apfelschorle 0,33l.webp',
    tags: [],
    order: 11,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Fritz Mischmasch 0,33l',
    price: '3,42 €',
    description: 'Die Spezi des Nordens, mit Inhalten des Südens: Das perfekte Mischverhältnis aus Cola und viel Frucht. • zzgl. Pfand (0,08 €), 0,33l, 10,36 €/1l, Enthält Koffein (6mg/100ml)',
    image: '/HIRO BURGER/Fritz Mischmasch 0,33l.webp',
    tags: [],
    order: 12,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Rauch Eistee Pfirsich 0,33l',
    price: '3,35 €',
    description: 'zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l',
    image: '/HIRO BURGER/Rauch Eistee Pfirsich 0,33l.webp',
    tags: [],
    order: 13,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Rauch Eistee Granatapfel 0,33l',
    price: '3,35 €',
    description: 'zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l',
    image: '/HIRO BURGER/Rauch Eistee Granatapfel 0,33l.webp',
    tags: [],
    order: 14,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Rauch Eistee Zitrone 0,33l',
    price: '3,35 €',
    description: 'zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l',
    image: '/HIRO BURGER/Rauch Eistee Zitrone 0,33l.webp',
    tags: [],
    order: 15,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Rauch Eistee Kirsche 0,33l',
    price: '3,35 €',
    description: 'zzgl. Pfand (0,15 €), 0,33l, 10,15 €/1l',
    image: '/HIRO BURGER/Rauch Eistee Kirsche 0,33l.webp',
    tags: [],
    order: 16,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Aqua Morelli Wasser Still 0,25l',
    price: '2,85 €',
    description: 'zzgl. Pfand (0,15 €), 0,25l, 11,40 €/1l',
    image: '/HIRO BURGER/Aqua Morelli Wasser Still 0,25l.webp',
    tags: [],
    order: 17,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Aqua Morelli Mineralwasser Sprudel 0,25l',
    price: '2,85 €',
    description: 'zzgl. Pfand (0,15 €), 0,25l, 11,40 €/1l',
    image: '/HIRO BURGER/Aqua Morelli Mineralwasser Sprudel 0,25l.webp',
    tags: [],
    order: 18,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Becks Blue',
    price: '3,50 €',
    description: 'alkoholfrei • 0,33l, 10,61 €/1l',
    image: '/HIRO BURGER/Becks Blue.webp',
    tags: [],
    order: 19,
    active: true,
  },
  {
    restaurant: 'DRINKS',
    section: 'Alkoholfreie Getränke',
    name: 'Franziskaner Weissbier',
    price: '3,50 €',
    description: 'alkoholfreie • 0,33l, 10,61 €/1l',
    image: '/HIRO BURGER/Franziskaner Weissbier.webp',
    tags: [],
    order: 20,
    active: true,
  },
]
