// LOS TACOS Menu Items - Complete Data

export const losTacosMenuItems = [
  // Beliebt Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Beliebt',
    name: 'The Chicken Taco',
    price: '8,90 €',
    description: 'mit Paprika, Mais, karamellisierten Zwiebeln, Hähnchenbrustfilet, Cheddar und hausgemachter Tacosauce',
    image: '/LOS TACOS/The Chicken Taco.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Beliebt',
    name: 'Original Birria Tacos (2 Stück)',
    price: '11,90 €',
    description: 'mit Maistortillas, Birria Pulled Beef, Rote Zwiebel-Koriander und Limetten',
    image: '/LOS TACOS/Original Birria Tacos (2 Stück).webp',
    tags: [],
    order: 2,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Beliebt',
    name: 'Burritos',
    price: '11,90 €',
    description: 'mit mexikanischem Tomatenreis, Grillgemüse, Tomatenwürfeln, Eisbergsalat, Guacamole, Kidneybohnen, Cheddar und hausgemachter Sauce',
    image: '/LOS TACOS/Burritos.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Dein Protein:',
        required: true,
        multiple: false,
        options: [
          { label: 'mit Chicken', price: 0 },
          { label: 'mit Halloumi', price: 0 },
          { label: 'mit Falafel', price: 0 },
          { label: 'mit Hiro Beef', price: 0 },
          { label: 'mit Honey BBQ Chicken', price: 0 },
          { label: 'mit Pulled Pork', price: 0 },
          { label: 'ohne Protein', price: 0 }
        ]
      },
      {
        title: 'Deine Extras - Proteine:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Falafel', price: 3.00 },
          { label: 'mit Chicken', price: 3.00 },
          { label: 'mit Halloumi', price: 3.00 },
          { label: 'mit Pulled Pork', price: 3.00 },
          { label: 'mit Honey BBQ Chicken', price: 3.00 },
          { label: 'mit Hiro Beef', price: 3.00 }
        ]
      },
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 3,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Beliebt',
    name: 'O.G. Taco Burger',
    price: '6,90 €',
    description: 'Saftiges Rindfleisch-Patty im knusprigen Taco-Style: gefüllt mit frischem Eisbergsalat, karamellisierte Zwiebeln, Cheddar und Ketchup und American Mustard',
    image: '/LOS TACOS/O.G. Taco Burger.webp',
    tags: [],
    order: 4,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Beliebt',
    name: 'Mexican Nachos',
    price: '6,90 €',
    description: 'mit Mexikanischer Tomatensalsa, Guacamole, Sour Cream',
    image: '/LOS TACOS/Mexican Nachos.webp',
    tags: [],
    order: 5,
    active: true,
  },

  // Fingerfood Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Pommes Frites',
    price: '4,90 €',
    description: 'mit Meersalz',
    image: '/LOS TACOS/Pommes Frites.webp',
    tags: ['Vegan', 'Vegetarisch'],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Süßkartoffel Pommes frites',
    price: '5,90 €',
    description: '',
    image: '/LOS TACOS/Süßkartoffel Pommes frites.webp',
    tags: ['Vegan', 'Vegetarisch'],
    order: 2,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Gurken Kimchi',
    price: '5,90 €',
    description: 'koreanisches Gurken-Kimchi mit gerösteten Sesam',
    image: '/LOS TACOS/Gurken Kimchi.webp',
    tags: ['Scharf'],
    order: 3,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Chicken Nuggets (8 Stück)',
    price: '6,90 €',
    description: 'knusprig frittierte Hähnchen Nuggets',
    image: '/LOS TACOS/Chicken Nuggets (8 Stück).webp',
    tags: [],
    order: 4,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Onion Rings (7 Stück)',
    price: '5,90 €',
    description: 'panierter Zwiebelringen',
    image: '/LOS TACOS/Onion Rings (7 Stück).webp',
    tags: ['Vegetarisch'],
    order: 5,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fingerfood',
    name: 'Mozzarella Sticks (7 Stück)',
    price: '5,90 €',
    description: 'mit Kräuterpanade',
    image: '/LOS TACOS/Mozzarella Sticks (7 Stück).webp',
    tags: ['Vegetarisch'],
    order: 6,
    active: true,
  },

  // Fresh Salads Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Fresh Salads',
    name: 'Mexikanischer Salat',
    price: '7,90 €',
    description: 'mit Nachos, Kirschtomaten, Mais, schwarze Bohnen, Kidneybohnen, Avocado, Paprika, Olivenöl, Limettensaft',
    image: '/LOS TACOS/Mexikanischer Salat.webp',
    tags: ['Vegetarisch'],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Fresh Salads',
    name: 'Mexikanische Tomatensalsa',
    price: '4,90 €',
    description: '',
    image: '/LOS TACOS/Mexikanische Tomatensalsa.webp',
    tags: ['Vegan', 'Vegetarisch'],
    order: 2,
    active: true,
  },

  // Birria Tacos Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Birria Tacos',
    name: 'Original Birria Tacos (2 Stück)',
    price: '11,90 €',
    description: 'mit Maistortillas, Birria Pulled Beef, Rote Zwiebel-Koriander und Limetten',
    image: '/LOS TACOS/Original Birria Tacos (2 Stück).webp',
    tags: [],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Birria Tacos',
    name: 'Birria Ramen',
    price: '14,90 €',
    description: 'Eine tief aromatische, hausgekochte Birria-Brühe, stundenlang eingekocht wie beim klassischen Ramen. Dazu zartes Birria-Fleisch, knackiges Gemüse und perfekt gegarte Nudeln',
    image: '',
    tags: ['Scharf'],
    order: 2,
    active: true,
  },

  // French Tacos Section
  {
    restaurant: 'LOS_TACOS',
    section: 'French Tacos',
    name: 'The Chicken Taco',
    price: '8,90 €',
    description: 'mit Paprika, Mais, karamellisierten Zwiebeln, Hähnchenbrustfilet, Cheddar und hausgemachter Tacosauce',
    image: '/LOS TACOS/The Chicken Taco.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'French Tacos',
    name: 'Beef Taco',
    price: '8,90 €',
    description: 'mit Paprika, Mais, karamellisierten Zwiebeln, 150g Rindfleisch Patty, Cheddar und hausgemachter Tacosauce',
    image: '/LOS TACOS/Beef Taco.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 2,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'French Tacos',
    name: 'Pulled Pork Taco',
    price: '8,90 €',
    description: 'mit Paprika, Mais, karamellisierten Zwiebeln, Pulled Pork, Barbecue-Limettensauce, Cheddar und hausgemachter Tacosauce',
    image: '/LOS TACOS/Pulled Pork Taco.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 3,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'French Tacos',
    name: 'Falafel Taco',
    price: '8,90 €',
    description: 'mit Paprika, Mais, karamellisierten Zwiebeln, Mozzarella, Falafel, veganem Käse und hausgemachter Tacosauce',
    image: '/LOS TACOS/Falafel Taco.webp',
    tags: ['Vegetarisch'],
    customizationGroups: [
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 4,
    active: true,
  },

  // Taco-Burger Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Taco-Burger',
    name: 'O.G. Taco Burger',
    price: '6,90 €',
    description: 'Saftiges Rindfleisch-Patty im knusprigen Taco-Style: gefüllt mit frischem Eisbergsalat, karamellisierte Zwiebeln, Cheddar und Ketchup und American Mustard',
    image: '/LOS TACOS/O.G. Taco Burger.webp',
    tags: [],
    order: 1,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Taco-Burger',
    name: 'BBQ-Bacon Taco-Burger',
    price: '6,90 €',
    description: 'Saftiges Rindfleisch-Patty im knusprigen Taco-Style: gefüllt mit frischem Eisbergsalat, karamellisierte Zwiebeln, Cheddar, knusprigen Bacon und BBQ-Sauce',
    image: '/LOS TACOS/BBQ-Bacon Taco-Burger.webp',
    tags: [],
    order: 2,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Taco-Burger',
    name: 'Chili-Cheese Taco-Burger',
    price: '6,90 €',
    description: 'Saftiges Rindfleisch-Patty im knusprigen Taco-Style: gefüllt mit frischem Eisbergsalat, karamellisierte Zwiebeln, Cheddar, homemade Chili-Chutney, frischen Peperoni und hauseigener Sauce',
    image: '/LOS TACOS/Chili-Cheese Taco-Burger.webp',
    tags: ['Scharf'],
    order: 3,
    active: true,
  },
  {
    restaurant: 'LOS_TACOS',
    section: 'Taco-Burger',
    name: 'Trüffel Parmesan Taco-Burger',
    price: '7,90 €',
    description: 'Saftiges Rindfleisch-Patty im knusprigen Taco-Style: gefüllt mit frischem Eisbergsalat, karamellisierte Zwiebeln, Cheddar, gehobeltem Parmesan und Trüffelmayonnaise',
    image: '/LOS TACOS/Trüffel Parmesan Taco-Burger.webp',
    tags: [],
    order: 4,
    active: true,
  },

  // Burritos Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Burritos',
    name: 'Burritos',
    price: '11,90 €',
    description: 'mit mexikanischem Tomatenreis, Grillgemüse, Tomatenwürfeln, Eisbergsalat, Guacamole, Kidneybohnen, Cheddar und hausgemachter Sauce',
    image: '/LOS TACOS/Burritos.webp',
    tags: [],
    customizationGroups: [
      {
        title: 'Dein Protein:',
        required: true,
        multiple: false,
        options: [
          { label: 'mit Chicken', price: 0 },
          { label: 'mit Halloumi', price: 0 },
          { label: 'mit Falafel', price: 0 },
          { label: 'mit Hiro Beef', price: 0 },
          { label: 'mit Honey BBQ Chicken', price: 0 },
          { label: 'mit Pulled Pork', price: 0 },
          { label: 'ohne Protein', price: 0 }
        ]
      },
      {
        title: 'Deine Extras - Proteine:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Falafel', price: 3.00 },
          { label: 'mit Chicken', price: 3.00 },
          { label: 'mit Halloumi', price: 3.00 },
          { label: 'mit Pulled Pork', price: 3.00 },
          { label: 'mit Honey BBQ Chicken', price: 3.00 },
          { label: 'mit Hiro Beef', price: 3.00 }
        ]
      },
      {
        title: 'Deine Extras - Mix Ins:',
        required: false,
        multiple: true,
        options: [
          { label: 'mit Cheddar', price: 1.00 },
          { label: 'mit Guacamole', price: 2.00 },
          { label: 'mit Zwiebeln, karamellisiert', price: 1.00 },
          { label: 'mit Paprika', price: 1.00 },
          { label: 'mit Avocado', price: 2.00 },
          { label: 'mit Petersilie', price: 1.00 },
          { label: 'mit Koriander', price: 1.00 },
          { label: 'mit Lauchzwiebeln', price: 1.00 },
          { label: 'mit Zwiebeln, rot', price: 1.00 },
          { label: 'mit Feta', price: 2.00 },
          { label: 'mit Kidneybohnen', price: 1.00 },
          { label: 'mit Eisbergsalat', price: 1.00 },
          { label: 'mit Mozzarella', price: 1.00 },
          { label: 'mit Gurken Kimchi', price: 2.00 },
          { label: 'mit Mais', price: 1.00 },
          { label: 'mit Tomatenreis', price: 2.00 },
          { label: 'mit Tomatensalsa', price: 1.00 },
          { label: 'mit Pommes frites', price: 2.00 }
        ]
      }
    ],
    order: 1,
    active: true,
  },

  // Loaded Nachos Section
  {
    restaurant: 'LOS_TACOS',
    section: 'Loaded Nachos',
    name: 'Mexican Nachos',
    price: '6,90 €',
    description: 'mit Mexikanischer Tomatensalsa, Guacamole, Sour Cream',
    image: '/LOS TACOS/Mexican Nachos.webp',
    tags: [],
    order: 1,
    active: true,
  },
]
